#!/bin/bash
# from https://stackoverflow.com/questions/13033799/how-to-make-ssh-add-read-passphrase-from-a-file
# requires expect (installed)

if [ $# -ne 2 ] ; then
  echo "Usage: ssh-add-pass keyfile passfile"
  exit 1
fi

pass=$(cat $2)

expect << EOF
  spawn ssh-add $1
  expect "Enter passphrase"
  send "$pass\r"
  expect eof
EOF
